server:
  port: 88
logging:
  level:
    cn.zqyu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gulimall-gateway
  cloud:
    gateway:
      routes:
        - id: gulimall-admin-api # 路由标示，必须唯一
          uri: lb://renren-fast # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/api/** # 路径断言，判断路径是否是以/user开头，如果是则符合
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

    nacos:
      server-addr: localhost:8848 # nacos地址